import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import AuthShowcase from "../components/AuthShowcase/AuthShowcase";
import { ChatBox } from "../components/ChatBox/ChatBox";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>(1) SocketTest</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col gap-16 bg-gradient-to-b  from-[#2e026d] to-[#15162c] p-16 text-white">
        <div className="w-full">
          <div className="flex justify-between">
            <div className="mt-1 text-5xl text-white">SocketTest</div>
            <div className="flex gap-8">
              <div className="mt-2 text-2xl text-white">Servers</div>
              <div className="mt-2 text-2xl text-white">Account</div>
            </div>
          </div>
        </div>
        <ChatBox />

        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;
